import asyncio
import html as html_mod
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from fastapi import HTTPException

from app.config import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SMTP_FROM_EMAIL


def _build_html(summary: str) -> str:
    """Build a professional HTML email that avoids spam triggers."""
    safe = html_mod.escape(summary)
    # Convert markdown-style **bold** to <strong> for nicer rendering
    import re as _re
    safe = _re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", safe)
    # Convert * bullets to styled list items
    lines = safe.split("\n")
    html_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("* "):
            html_lines.append(
                f'<tr><td style="padding:0 0 8px 0;vertical-align:top;width:20px;color:#3b82f6;font-size:16px;">&#8226;</td>'
                f'<td style="padding:0 0 8px 8px;line-height:1.6;color:#374151;font-size:14px;">{stripped[2:]}</td></tr>'
            )
        elif stripped:
            html_lines.append(
                f'<p style="margin:0 0 14px 0;line-height:1.7;color:#374151;font-size:14px;">{stripped}</p>'
            )
    # Wrap bullet rows in a table
    processed = []
    bullet_buf: list[str] = []
    for hl in html_lines:
        if hl.startswith("<tr>"):
            bullet_buf.append(hl)
        else:
            if bullet_buf:
                processed.append('<table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 16px 4px;">'
                                 + "".join(bullet_buf) + "</table>")
                bullet_buf = []
            processed.append(hl)
    if bullet_buf:
        processed.append('<table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 16px 4px;">'
                         + "".join(bullet_buf) + "</table>")
    body_html = "\n".join(processed)

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f1f5f9;font-family:'Segoe UI',Roboto,Arial,Helvetica,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f1f5f9;padding:40px 0;">
    <tr><td align="center">
      <!-- Main card -->
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.08);">
        <!-- Accent bar -->
        <tr><td style="height:4px;background:linear-gradient(90deg,#3b82f6,#8b5cf6,#06b6d4);"></td></tr>
        <!-- Header -->
        <tr>
          <td style="padding:32px 40px 24px 40px;">
            <table role="presentation" cellpadding="0" cellspacing="0" width="100%">
              <tr>
                <td>
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:#3b82f6;">Sales Insight Automator</p>
                  <h1 style="margin:8px 0 0;font-size:24px;color:#0f172a;font-weight:700;line-height:1.3;">Executive Summary Report</h1>
                  <p style="margin:6px 0 0;font-size:13px;color:#64748b;">AI-generated analysis of your sales dataset</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <!-- Divider -->
        <tr><td style="padding:0 40px;"><div style="height:1px;background-color:#e2e8f0;"></div></td></tr>
        <!-- Body -->
        <tr>
          <td style="padding:28px 40px 32px 40px;">
            {body_html}
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #e2e8f0;">
            <table role="presentation" cellpadding="0" cellspacing="0" width="100%">
              <tr>
                <td>
                  <p style="margin:0;font-size:12px;color:#64748b;">Generated by <strong style="color:#334155;">Sales Insight Automator</strong></p>
                  <p style="margin:4px 0 0;font-size:11px;color:#94a3b8;">Powered by Groq AI &middot; Delivered via SMTP</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <!-- Sub-footer -->
      <table role="presentation" width="600" cellpadding="0" cellspacing="0">
        <tr>
          <td style="padding:20px 40px 0;text-align:center;">
            <p style="margin:0;font-size:11px;color:#94a3b8;">If you did not request this report, you can safely ignore this email.</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


def _build_plain_text(summary: str) -> str:
    """Build a plain-text version (improves deliverability)."""
    return (
        "SALES INSIGHT REPORT\n"
        "====================\n\n"
        f"{summary}\n\n"
        "---\n"
        "Generated by Sales Insight Automator.\n"
        "If you did not request this report, you can safely ignore this email."
    )


def _send_smtp(to_email: str, html_body: str, text_body: str) -> None:
    """Blocking SMTP send — called via asyncio.to_thread."""
    if not all([SMTP_HOST, SMTP_USER, SMTP_PASSWORD]):
        raise HTTPException(status_code=500, detail="SMTP is not configured. Set SMTP_HOST, SMTP_USER, and SMTP_PASSWORD.")

    msg = MIMEMultipart("alternative")
    msg["From"] = SMTP_FROM_EMAIL
    msg["To"] = to_email
    msg["Subject"] = "Sales Insight Report - Executive Summary"

    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_FROM_EMAIL, to_email, msg.as_string())


async def send_email(to_email: str, summary: str) -> None:
    """Send the executive summary to the specified email via SMTP."""
    html_body = _build_html(summary)
    text_body = _build_plain_text(summary)

    try:
        await asyncio.to_thread(_send_smtp, to_email, html_body, text_body)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Failed to send email: {exc}")
