import asyncio
import html as html_mod
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import httpx
from fastapi import HTTPException

from app.config import (
    BREVO_API_KEY,
    RESEND_API_KEY,
    SENDGRID_API_KEY,
    SMTP_FROM_EMAIL,
    SMTP_HOST,
    SMTP_PASSWORD,
    SMTP_PORT,
    SMTP_USER,
)


def _build_html(summary: str) -> str:
    """Build a professional HTML email that avoids spam triggers."""
    safe = html_mod.escape(summary)
    # Convert markdown-style **bold** to <strong> for nicer rendering
    import re as _re
    safe = _re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", safe)
    # Convert * bullets to styled list items
    lines = safe.split("\n")
    html_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("* "):
            html_lines.append(
                f'<tr><td style="padding:0 0 8px 0;vertical-align:top;width:20px;color:#3b82f6;font-size:16px;">&#8226;</td>'
                f'<td style="padding:0 0 8px 8px;line-height:1.6;color:#374151;font-size:14px;">{stripped[2:]}</td></tr>'
            )
        elif stripped:
            html_lines.append(
                f'<p style="margin:0 0 14px 0;line-height:1.7;color:#374151;font-size:14px;">{stripped}</p>'
            )
    # Wrap bullet rows in a table
    processed = []
    bullet_buf: list[str] = []
    for hl in html_lines:
        if hl.startswith("<tr>"):
            bullet_buf.append(hl)
        else:
            if bullet_buf:
                processed.append('<table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 16px 4px;">'
                                 + "".join(bullet_buf) + "</table>")
                bullet_buf = []
            processed.append(hl)
    if bullet_buf:
        processed.append('<table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 16px 4px;">'
                         + "".join(bullet_buf) + "</table>")
    body_html = "\n".join(processed)

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f1f5f9;font-family:'Segoe UI',Roboto,Arial,Helvetica,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f1f5f9;padding:40px 0;">
    <tr><td align="center">
      <!-- Main card -->
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.08);">
        <!-- Accent bar -->
        <tr><td style="height:4px;background:linear-gradient(90deg,#3b82f6,#8b5cf6,#06b6d4);"></td></tr>
        <!-- Header -->
        <tr>
          <td style="padding:32px 40px 24px 40px;">
            <table role="presentation" cellpadding="0" cellspacing="0" width="100%">
              <tr>
                <td>
                  <p style="margin:0;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:#3b82f6;">Sales Insight Automator</p>
                  <h1 style="margin:8px 0 0;font-size:24px;color:#0f172a;font-weight:700;line-height:1.3;">Executive Summary Report</h1>
                  <p style="margin:6px 0 0;font-size:13px;color:#64748b;">AI-generated analysis of your sales dataset</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <!-- Divider -->
        <tr><td style="padding:0 40px;"><div style="height:1px;background-color:#e2e8f0;"></div></td></tr>
        <!-- Body -->
        <tr>
          <td style="padding:28px 40px 32px 40px;">
            {body_html}
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="padding:24px 40px;background-color:#f8fafc;border-top:1px solid #e2e8f0;">
            <table role="presentation" cellpadding="0" cellspacing="0" width="100%">
              <tr>
                <td>
                  <p style="margin:0;font-size:12px;color:#64748b;">Generated by <strong style="color:#334155;">Sales Insight Automator</strong></p>
                  <p style="margin:4px 0 0;font-size:11px;color:#94a3b8;">Powered by Groq AI &middot; Delivered via SMTP</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <!-- Sub-footer -->
      <table role="presentation" width="600" cellpadding="0" cellspacing="0">
        <tr>
          <td style="padding:20px 40px 0;text-align:center;">
            <p style="margin:0;font-size:11px;color:#94a3b8;">If you did not request this report, you can safely ignore this email.</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


def _build_plain_text(summary: str) -> str:
    """Build a plain-text version (improves deliverability)."""
    return (
        "SALES INSIGHT REPORT\n"
        "====================\n\n"
        f"{summary}\n\n"
        "---\n"
        "Generated by Sales Insight Automator.\n"
        "If you did not request this report, you can safely ignore this email."
    )


def _send_smtp(to_email: str, html_body: str, text_body: str) -> None:
    """Blocking SMTP send — tries SSL (465) first, then STARTTLS (587)."""
    if not all([SMTP_HOST, SMTP_USER, SMTP_PASSWORD]):
        raise HTTPException(status_code=500, detail="SMTP is not configured.")

    msg = MIMEMultipart("alternative")
    msg["From"] = SMTP_FROM_EMAIL
    msg["To"] = to_email
    msg["Subject"] = "Sales Insight Report - Executive Summary"
    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL(SMTP_HOST, 465, timeout=15) as server:
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_FROM_EMAIL, to_email, msg.as_string())
        return
    except Exception:
        pass

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_FROM_EMAIL, to_email, msg.as_string())


async def _send_sendgrid(to_email: str, html_body: str, text_body: str) -> None:
    """Send email via SendGrid HTTP API — free 100/day, any recipient."""
    print("[EMAIL] Using SendGrid HTTP API...", flush=True)
    from_email = SMTP_FROM_EMAIL or "singalmayank0000@gmail.com"
    async with httpx.AsyncClient(timeout=20) as client:
        response = await client.post(
            "https://api.sendgrid.com/v3/mail/send",
            headers={
                "Authorization": f"Bearer {SENDGRID_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "personalizations": [{"to": [{"email": to_email}]}],
                "from": {"email": from_email, "name": "Sales Insight Automator"},
                "subject": "Sales Insight Report - Executive Summary",
                "content": [
                    {"type": "text/plain", "value": text_body},
                    {"type": "text/html", "value": html_body},
                ],
            },
        )
    if response.status_code not in (200, 201, 202):
        print(f"[EMAIL] SendGrid error {response.status_code}: {response.text}", flush=True)
        raise HTTPException(status_code=502, detail=f"SendGrid API error ({response.status_code}): {response.text}")
    print("[EMAIL] SendGrid sent successfully.", flush=True)


async def _send_brevo(to_email: str, html_body: str) -> None:
    """Send email via Brevo (Sendinblue) HTTP API — free 300/day, any recipient."""
    print("[EMAIL] Using Brevo HTTP API...", flush=True)
    async with httpx.AsyncClient(timeout=20) as client:
        response = await client.post(
            "https://api.brevo.com/v3/smtp/email",
            headers={
                "api-key": BREVO_API_KEY,
                "Content-Type": "application/json",
            },
            json={
                "sender": {"name": "Sales Insight Automator", "email": SMTP_FROM_EMAIL or "singalmayank0000@gmail.com"},
                "to": [{"email": to_email}],
                "subject": "Sales Insight Report - Executive Summary",
                "htmlContent": html_body,
            },
        )
    if response.status_code not in (200, 201):
        print(f"[EMAIL] Brevo error {response.status_code}: {response.text}", flush=True)
        raise HTTPException(status_code=502, detail=f"Brevo API error ({response.status_code}): {response.text}")
    print("[EMAIL] Brevo sent successfully.", flush=True)


async def _send_resend(to_email: str, html_body: str) -> None:
    """Send email via Resend HTTP API."""
    print("[EMAIL] Using Resend HTTP API...", flush=True)
    async with httpx.AsyncClient(timeout=15) as client:
        response = await client.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {RESEND_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "from": "Sales Insight <onboarding@resend.dev>",
                "to": [to_email],
                "subject": "Sales Insight Report - Executive Summary",
                "html": html_body,
            },
        )
    if response.status_code not in (200, 201):
        print(f"[EMAIL] Resend error {response.status_code}: {response.text}", flush=True)
        raise HTTPException(status_code=502, detail=f"Resend API error ({response.status_code}): {response.text}")
    print("[EMAIL] Resend sent successfully.", flush=True)


async def send_email(to_email: str, summary: str) -> None:
    """Send email: SendGrid first, then Brevo, Resend, SMTP fallback."""
    html_body = _build_html(summary)
    text_body = _build_plain_text(summary)
    errors = []

    # 1. SendGrid HTTP API (free 100/day, any recipient)
    if SENDGRID_API_KEY:
        try:
            await _send_sendgrid(to_email, html_body, text_body)
            return
        except Exception as e:
            errors.append(f"SendGrid: {e}")

    # 2. Brevo HTTP API (sends to any email, free 300/day)
    if BREVO_API_KEY:
        try:
            await _send_brevo(to_email, html_body)
            return
        except Exception as e:
            errors.append(f"Brevo: {e}")

    # 3. Resend HTTP API
    if RESEND_API_KEY:
        try:
            await _send_resend(to_email, html_body)
            return
        except Exception as e:
            errors.append(f"Resend: {e}")

    # 4. SMTP fallback (works locally, blocked on Render)
    if all([SMTP_HOST, SMTP_USER, SMTP_PASSWORD]):
        try:
            await asyncio.to_thread(_send_smtp, to_email, html_body, text_body)
            return
        except Exception as e:
            errors.append(f"SMTP: {e}")

    detail = "; ".join(errors) if errors else "No email provider configured."
    print(f"[EMAIL] All providers failed: {detail}", flush=True)
    raise HTTPException(status_code=502, detail=f"Failed to send email. {detail}")
