from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

from app.config import ALLOWED_ORIGINS
from app.routes.analyze import router as analyze_router
from app.utils.rate_limiter import limiter

app = FastAPI(
    title="Sales Insight Automator",
    description=(
        "AI-powered sales analytics API.\n\n"
        "Upload a CSV/XLSX sales dataset and receive an executive summary "
        "generated by Groq Llama 3, delivered to your inbox via SMTP.\n\n"
        "**Security:** CORS protection, rate limiting (10 req/min), "
        "file type & size validation (5 MB), email validation."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# --------------- Middleware ---------------
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["POST", "GET", "OPTIONS"],
    allow_headers=["*"],
)

# --------------- Routes ---------------
app.include_router(analyze_router)


@app.get("/health", tags=["System"], summary="Health check")
async def health_check():
    """Returns service health status. Used by Docker healthcheck and monitoring."""
    return {"status": "healthy"}
