from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

from app.config import ALLOWED_ORIGINS
from app.routes.analyze import router as analyze_router
from app.utils.rate_limiter import limiter

app = FastAPI(
    title="Sales Insight Automator",
    description=(
        "AI-powered sales analytics API.\n\n"
        "Upload a CSV/XLSX sales dataset and receive an executive summary "
        "generated by Groq Llama 3, delivered to your inbox via SMTP.\n\n"
        "**Security:** CORS protection, rate limiting (10 req/min), "
        "file type & size validation (5 MB), email validation."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# --------------- Middleware ---------------
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["POST", "GET", "OPTIONS"],
    allow_headers=["*"],
)

# --------------- Routes ---------------
app.include_router(analyze_router)


@app.get("/health", tags=["System"], summary="Health check")
async def health_check():
    """Returns service health status. Used by Docker healthcheck and monitoring."""
    return {"status": "healthy"}


@app.get("/config-check", tags=["System"], summary="Verify environment config")
async def config_check():
    """Check which required environment variables are set (values are not revealed)."""
    from app.config import GROQ_API_KEY, SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SMTP_FROM_EMAIL, ALLOWED_ORIGINS
    return {
        "GROQ_API_KEY": bool(GROQ_API_KEY),
        "SMTP_HOST": bool(SMTP_HOST),
        "SMTP_PORT": SMTP_PORT,
        "SMTP_USER": bool(SMTP_USER),
        "SMTP_PASSWORD": bool(SMTP_PASSWORD),
        "SMTP_FROM_EMAIL": bool(SMTP_FROM_EMAIL),
        "ALLOWED_ORIGINS": ALLOWED_ORIGINS,
    }


@app.get("/test-groq", tags=["System"], summary="Test Groq API connection")
async def test_groq():
    """Quick test of Groq API connectivity."""
    import httpx
    from app.config import GROQ_API_KEY
    print("[TEST-GROQ] Starting...", flush=True)
    if not GROQ_API_KEY:
        return {"ok": False, "error": "GROQ_API_KEY is empty"}
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            r = await client.post(
                "https://api.groq.com/openai/v1/chat/completions",
                headers={"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"},
                json={"model": "llama-3.3-70b-versatile", "messages": [{"role": "user", "content": "Say hello"}], "max_tokens": 10},
            )
        print(f"[TEST-GROQ] Status: {r.status_code}", flush=True)
        if r.status_code == 200:
            return {"ok": True, "response": r.json()["choices"][0]["message"]["content"]}
        return {"ok": False, "status": r.status_code, "body": r.text[:500]}
    except Exception as e:
        print(f"[TEST-GROQ] Error: {e}", flush=True)
        return {"ok": False, "error": str(e)}


@app.get("/test-smtp", tags=["System"], summary="Test SMTP connection")
async def test_smtp():
    """Quick test of SMTP connectivity."""
    import smtplib
    from app.config import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD
    print("[TEST-SMTP] Starting...", flush=True)
    if not all([SMTP_HOST, SMTP_USER, SMTP_PASSWORD]):
        return {"ok": False, "error": "SMTP config missing"}
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
        print("[TEST-SMTP] Login OK", flush=True)
        return {"ok": True, "message": "SMTP login successful"}
    except Exception as e:
        print(f"[TEST-SMTP] Error: {e}", flush=True)
        return {"ok": False, "error": str(e)}
